use std::any::TypeId;

#[test]
fn facade_exports_are_the_canonical_core_types() {
    assert_eq!(
        TypeId::of::<safemlx_lm::ModelKind>(),
        TypeId::of::<safemlx_lm::core::artifact::ModelKind>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::GgufArchitecture>(),
        TypeId::of::<safemlx_lm::core::artifact::GgufArchitecture>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::PreparationPolicy>(),
        TypeId::of::<safemlx_lm::core::artifact::PreparationPolicy>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::ModelPreparationPlan>(),
        TypeId::of::<safemlx_lm::core::artifact::ModelPreparationPlan>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::AttentionPolicy>(),
        TypeId::of::<safemlx_lm::core::attention::AttentionPolicy>(),
    );
    let schedule = safemlx_lm::LayerSchedule::all_full(2).unwrap();
    assert_eq!(schedule.len(), 2);
    assert_eq!(
        TypeId::of::<safemlx_lm::RequestId>(),
        TypeId::of::<safemlx_lm::core::scheduler::RequestId>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::SchedulerLimits>(),
        TypeId::of::<safemlx_lm::core::scheduler::SchedulerLimits>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::SchedulerReport>(),
        TypeId::of::<safemlx_lm::core::scheduler::SchedulerReport>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::SchedulerError>(),
        TypeId::of::<safemlx_lm::core::scheduler::SchedulerError>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::FinishReason>(),
        TypeId::of::<safemlx_lm::core::generation::FinishReason>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::SemanticEvent>(),
        TypeId::of::<safemlx_lm::core::generation::SemanticEvent>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::GenerationConfigOverrides>(),
        TypeId::of::<safemlx_lm::core::generation::GenerationConfigOverrides>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::MtpConfig>(),
        TypeId::of::<safemlx_lm::core::generation::MtpConfig>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::MtpSchedulerOptions>(),
        TypeId::of::<safemlx_lm::core::generation::MtpSchedulerOptions>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::runtime::generation::speculative::MtpStats>(),
        TypeId::of::<safemlx_lm::core::speculative::MtpStats>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::runtime::generation::speculative::MtpSchedulerStats>(),
        TypeId::of::<safemlx_lm::core::speculative::MtpSchedulerStats>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::runtime::generation::speculative::MtpBatchOutput>(),
        TypeId::of::<safemlx_lm::core::speculative::MtpBatchOutput>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::OffloadConfig>(),
        TypeId::of::<safemlx_lm::core::residency::OffloadConfig>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::MemoryTier>(),
        TypeId::of::<safemlx_lm::core::residency::MemoryTier>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::OffloadReport>(),
        TypeId::of::<safemlx_lm::core::residency::OffloadReport>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::ResidencyLedger>(),
        TypeId::of::<safemlx_lm::core::residency::ResidencyLedger>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::ResidencyLedgerError>(),
        TypeId::of::<safemlx_lm::core::residency::ResidencyLedgerError>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::UnitResidencyReport>(),
        TypeId::of::<safemlx_lm::core::residency::UnitResidencyReport>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::BackgroundPrefetchReport>(),
        TypeId::of::<safemlx_lm::core::residency::BackgroundPrefetchReport>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::CacheIoExecutionState>(),
        TypeId::of::<safemlx_lm::core::cache::CacheIoExecutionState>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::CachePoolLimits>(),
        TypeId::of::<safemlx_lm::core::cache::CachePoolLimits>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::CacheResidencyPool>(),
        TypeId::of::<safemlx_lm::core::cache::CacheResidencyPool>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::CachePoolReport>(),
        TypeId::of::<safemlx_lm::core::cache::CachePoolReport>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::CacheBlockId>(),
        TypeId::of::<safemlx_lm::core::cache::CacheBlockId>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::LayerCachePolicy>(),
        TypeId::of::<safemlx_lm::core::cache::LayerCachePolicy>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::StateTensorPolicy>(),
        TypeId::of::<safemlx_lm::core::cache::StateTensorPolicy>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::PromptCacheDescriptor>(),
        TypeId::of::<safemlx_lm::core::cache::PromptCacheDescriptor>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::PromptCacheManifest>(),
        TypeId::of::<safemlx_lm::core::cache::PromptCacheManifest>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::PromptCacheTopology>(),
        TypeId::of::<safemlx_lm::core::cache::PromptCacheTopology>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::CacheBlockLifecycle>(),
        TypeId::of::<safemlx_lm::core::cache::CacheBlockLifecycle>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::MutableCacheTail>(),
        TypeId::of::<safemlx_lm::core::cache::MutableCacheTail>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::CacheLifecycleError>(),
        TypeId::of::<safemlx_lm::core::cache::CacheLifecycleError>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::CacheStoragePhase>(),
        TypeId::of::<safemlx_lm::core::cache::CacheStoragePhase>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::CacheIoOperationKey>(),
        TypeId::of::<safemlx_lm::core::cache::CacheIoOperationKey>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::CacheStorageError>(),
        TypeId::of::<safemlx_lm::core::cache::CacheStorageError>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::DistributedCapabilities>(),
        TypeId::of::<safemlx_lm::core::backend::DistributedCapabilities>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::CollectiveScope>(),
        TypeId::of::<safemlx_lm::core::backend::CollectiveScope>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::DistributedSessionDescriptor>(),
        TypeId::of::<safemlx_lm::core::backend::DistributedSessionDescriptor>(),
    );
    assert_eq!(
        TypeId::of::<safemlx_lm::ValueDescriptor>(),
        TypeId::of::<safemlx_lm::core::backend::ValueDescriptor>(),
    );
}
