//! Logical semantic history retained by controlled delivery, separate from a
//! consumer's encoded trace. Allocator capacity/overhead is not measured here.

/// Bounds additional history after the already-retained prefix has been counted.
///
/// `Delivery::send` charges a complete `ControlledGenerationRecord` before cloning
/// its semantic event. JSON encodes every owned string in `SemanticEvent` with at
/// least its UTF-8 length. Even the smallest record's fixed fields exceed the
/// event's inline size, including string descriptors. Therefore each retained
/// event's logical storage is at most its charged record length, including empty
/// deltas, tool boundaries and termination. Tests below check the wire/storage
/// relationship with minimum metadata and every event variant.
///
/// Nonsemantic records also consume trace capacity, making this conservative.
/// Restore never refunds emitted bytes. A fresh branch uses zero emitted bytes;
/// its source reservation accounts for the inherited history independently.
pub(super) fn semantic_history_growth_bound(trace_limit: u64, emitted_bytes: u64) -> u64 {
    trace_limit.saturating_sub(emitted_bytes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::api::{
        ControlledGenerationRecord, ObservedGenerationEvent, ObservedGenerationRecord,
    };
    use crate::runtime::generation::storage::SnapshotStorage;
    use eredu_core::{FinishReason, SemanticEvent};
    use eredu_runtime::execution_control::{TraceBudget, TraceLimits};

    // Minimize attribution and numeric widths rather than relying on the long IDs
    // currently generated by the facade. Escaping and longer fields only add bytes.
    fn record(event: SemanticEvent) -> ControlledGenerationRecord {
        ControlledGenerationRecord {
            schema_version: 0,
            sequence: 0,
            epoch: 0,
            timing: Default::default(),
            generation: ObservedGenerationRecord {
                schema_version: 0,
                run_id: String::new(),
                artifact_identity: None,
                session_id: String::new(),
                capture_plan_id: String::new(),
                intervention_plan_id: None,
                parameter_overlay_id: None,
                event: ObservedGenerationEvent::Semantic {
                    prediction_index: Some(0),
                    event,
                },
            },
        }
    }

    #[test]
    fn semantic_history_is_bounded_by_charged_records_for_every_event_variant() {
        let mut events = vec![SemanticEvent::ToolCallEnd];
        for reason in [
            FinishReason::Eos,
            FinishReason::StopSequence,
            FinishReason::GrammarComplete,
            FinishReason::MaxTokens,
            FinishReason::Cancelled,
        ] {
            events.push(SemanticEvent::Finished { reason });
        }
        for value in [
            String::new(),
            "a".into(),
            "\"\\\n\0é🙂".into(),
            "x".repeat(65536),
        ] {
            events.extend([
                SemanticEvent::TextDelta(value.clone()),
                SemanticEvent::ReasoningDelta(value.clone()),
                SemanticEvent::ToolCallStart {
                    index: 0,
                    id: value.clone(),
                    name: value.clone(),
                },
                SemanticEvent::ToolArgumentsDelta {
                    index: 0,
                    json_fragment: value,
                },
            ]);
        }
        let limits = TraceLimits {
            per_record_bytes: 1 << 20,
            total_bytes: 64 << 20,
        };
        let mut budget = TraceBudget::new(limits);
        let mut retained = 0;
        for event in events {
            let logical = event.snapshot_bytes().unwrap();
            let record = record(event);
            let before = budget.emitted_bytes();
            budget.charge(&record).unwrap();
            let charged = budget.emitted_bytes() - before;
            assert!(
                logical <= charged,
                "{logical} retained bytes exceed {charged} charged bytes: {:?}",
                record.generation.event
            );
            retained += logical;
            assert!(
                retained
                    + semantic_history_growth_bound(limits.total_bytes, budget.emitted_bytes())
                    <= limits.total_bytes
            );
        }
        assert_eq!(
            semantic_history_growth_bound(limits.total_bytes, limits.total_bytes),
            0
        );
        assert_eq!(semantic_history_growth_bound(0, 1), 0);
        assert_eq!(semantic_history_growth_bound(u64::MAX, 0), u64::MAX);
    }
}
