// Adapted from SLEEF xexpf, revision 5a1d179df9cf652951b59010a2d2075372d67f68.
// Copyright Naoki Shibata and contributors 2010 - 2024.
// The original polynomial is retained with explicit fused multiply-adds.
// https://github.com/shibatch/sleef/blob/5a1d179df9cf652951b59010a2d2075372d67f68/src/libm/sleefsimdsp.c
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#pragma once

// Stable one-ULP exponential for maximum-subtracted scores and activation functions.
// Explicit rounding keeps rare BF16 halfway cases independent of libm/SIMD ABI.
inline float stable_exp_f32(float d) {
  if (!metal::isfinite(d)) return metal::precise::exp(d);
  if (d > 100.0f) return INFINITY;
  if (d < -104.0f) return 0.0f;
  int q = static_cast<int>(metal::rint(d * 1.44269504088896340736f));
  float s = metal::fma(float(q), -0.693145751953125f, d);
  s = metal::fma(float(q), -1.428606765330187045e-06f, s);
  float u = 0.000198527617612853646278381f;
  u = metal::fma(u, s, 0.00139304355252534151077271f);
  u = metal::fma(u, s, 0.00833336077630519866943359f);
  u = metal::fma(u, s, 0.0416664853692054748535156f);
  u = metal::fma(u, s, 0.166666671633720397949219f);
  u = metal::fma(u, s, 0.5f);
  u = 1.0f + metal::fma(s * s, u, s);
  return metal::ldexp(metal::ldexp(u, q >> 1), q - (q >> 1));
}
