# Copy already verified/patched inputs to stable compilation paths. Metadata is
# outside both source trees. Only one configure/build may own these paths.
cmake_minimum_required(VERSION 3.21)

foreach(required SOURCE_DIR DESTINATION_DIR STATE_DIR IDENTITY)
  if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
    message(FATAL_ERROR "Missing source mirror argument: ${required}")
  endif()
endforeach()
string(LENGTH "${IDENTITY}" identity_length)
if(NOT identity_length EQUAL 64 OR NOT IDENTITY MATCHES "^[0-9a-f]+$")
  message(FATAL_ERROR "Source mirror identity must be a SHA256 value")
endif()
foreach(path SOURCE_DIR DESTINATION_DIR STATE_DIR)
  if(NOT IS_ABSOLUTE "${${path}}" OR IS_SYMLINK "${${path}}")
    message(FATAL_ERROR "Source mirror paths must be absolute, non-symlink roots")
  endif()
  file(REAL_PATH "${${path}}" ${path})
endforeach()
foreach(left SOURCE_DIR DESTINATION_DIR STATE_DIR)
  foreach(right SOURCE_DIR DESTINATION_DIR STATE_DIR)
    if(NOT left STREQUAL right)
      string(FIND "${${left}}/" "${${right}}/" nested)
      if(nested EQUAL 0)
        message(FATAL_ERROR "Source mirror roots must be disjoint")
      endif()
    endif()
  endforeach()
endforeach()
file(MAKE_DIRECTORY "${STATE_DIR}")
file(REMOVE "${STATE_DIR}/completed.txt")
if(NOT IS_DIRECTORY "${SOURCE_DIR}" OR NOT EXISTS "${SOURCE_DIR}/CMakeLists.txt")
  message(FATAL_ERROR "Prepared source is incomplete: ${SOURCE_DIR}")
endif()

function(check_relative path)
  if(IS_ABSOLUTE "${path}" OR "${path}" STREQUAL "" OR
     "${path}" MATCHES "(^|/)\\.\\.?(/|$)" OR "${path}" MATCHES "[;\r\n]")
    message(FATAL_ERROR "Invalid owned source path: ${path}")
  endif()
endfunction()

# A failed refresh may already have added paths. Its pending union keeps those
# paths owned so a retry can remove them even when the next revision omits them.
set(owned)
foreach(manifest owned.txt pending.txt)
  if(EXISTS "${STATE_DIR}/${manifest}")
    file(STRINGS "${STATE_DIR}/${manifest}" previous)
    foreach(path IN LISTS previous)
      check_relative("${path}")
      list(APPEND owned "${path}")
    endforeach()
  endif()
endforeach()
list(REMOVE_DUPLICATES owned)
file(GLOB_RECURSE incoming LIST_DIRECTORIES true RELATIVE "${SOURCE_DIR}"
     "${SOURCE_DIR}/*")
foreach(path IN LISTS incoming)
  check_relative("${path}")
  if(IS_SYMLINK "${SOURCE_DIR}/${path}" OR NOT EXISTS "${SOURCE_DIR}/${path}")
    message(FATAL_ERROR "Unsupported prepared source entry: ${path}")
  endif()
endforeach()
file(GLOB_RECURSE existing LIST_DIRECTORIES true RELATIVE "${DESTINATION_DIR}"
     "${DESTINATION_DIR}/*")
set(obsolete)
foreach(path IN LISTS existing)
  check_relative("${path}")
  if(IS_SYMLINK "${DESTINATION_DIR}/${path}" OR NOT path IN_LIST owned)
    message(FATAL_ERROR "Refusing unowned compilation source entry: ${path}")
  endif()
  if(NOT path IN_LIST incoming OR
     (IS_DIRECTORY "${SOURCE_DIR}/${path}" AND NOT IS_DIRECTORY "${DESTINATION_DIR}/${path}") OR
     (NOT IS_DIRECTORY "${SOURCE_DIR}/${path}" AND IS_DIRECTORY "${DESTINATION_DIR}/${path}"))
    list(APPEND obsolete "${path}")
  endif()
endforeach()
set(pending ${owned} ${incoming})
list(REMOVE_DUPLICATES pending)
list(SORT pending)
string(REPLACE ";" "\n" pending_text "${pending}")
file(WRITE "${STATE_DIR}/pending.tmp" "${pending_text}\n")
file(RENAME "${STATE_DIR}/pending.tmp" "${STATE_DIR}/pending.txt")

# Children precede parents. Never recursively remove a directory containing an
# unowned/generated file; the preflight above and empty-directory check protect it.
list(SORT obsolete ORDER DESCENDING)
foreach(path IN LISTS obsolete)
  if(IS_DIRECTORY "${DESTINATION_DIR}/${path}")
    file(GLOB children "${DESTINATION_DIR}/${path}/*")
    if(children)
      message(FATAL_ERROR "Compilation source directory is not empty: ${path}")
    endif()
    file(REMOVE_RECURSE "${DESTINATION_DIR}/${path}")
  else()
    file(REMOVE "${DESTINATION_DIR}/${path}")
  endif()
  if(EXISTS "${DESTINATION_DIR}/${path}")
    message(FATAL_ERROR "Could not remove stale compilation source: ${path}")
  endif()
endforeach()
file(MAKE_DIRECTORY "${DESTINATION_DIR}")
foreach(path IN LISTS incoming)
  if(IS_DIRECTORY "${SOURCE_DIR}/${path}")
    file(MAKE_DIRECTORY "${DESTINATION_DIR}/${path}")
  else()
    get_filename_component(parent "${DESTINATION_DIR}/${path}" DIRECTORY)
    file(MAKE_DIRECTORY "${parent}")
    file(COPY_FILE "${SOURCE_DIR}/${path}" "${DESTINATION_DIR}/${path}"
         ONLY_IF_DIFFERENT RESULT copied)
    if(NOT copied STREQUAL "0")
      message(FATAL_ERROR "Could not refresh compilation source ${path}: ${copied}")
    endif()
  endif()
endforeach()
list(SORT incoming)
string(REPLACE ";" "\n" owned_text "${incoming}")
file(WRITE "${STATE_DIR}/owned.tmp" "${owned_text}\n")
file(RENAME "${STATE_DIR}/owned.tmp" "${STATE_DIR}/owned.txt")
file(REMOVE "${STATE_DIR}/pending.txt")
file(WRITE "${STATE_DIR}/completed.tmp" "${IDENTITY}\n")
file(RENAME "${STATE_DIR}/completed.tmp" "${STATE_DIR}/completed.txt")
