[package]
name = "safemlx-tests"
edition.workspace = true
rust-version.workspace = true
version = "0.1.0"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[features]
cuda = ["safemlx/cuda"]
nccl = ["cuda", "safemlx/nccl"]

[dependencies]

[dev-dependencies]
safemlx-internal-macros.workspace = true
safemlx = { workspace = true, features = ["accelerate", "metal", "safetensors"] }
tempfile.workspace = true
