//! Compare the MLX realtime backend with a released PersonaPlex 7B-v1
//! PyTorch fixture generated by `scripts/personaplex_torch_fixture.py`.
//!
//! Generate and run explicitly:
//!
//! ```text
//! python scripts/personaplex_torch_fixture.py \
//!   --artifact-dir /models/personaplex-7b-v1 \
//!   --checkpoint /models/personaplex-7b-v1 \
//!   --personaplex-source /src/personaplex \
//!   --moshi-source /src/kyutai-moshi/moshi \
//!   --require-torch-version VERSION \
//!   --output /fixtures/personaplex-7b-v1-greedy.safetensors
//! cargo run -p eredu-backend-mlx --example personaplex_torch_parity -- \
//!   /models/personaplex-7b-v1 /fixtures/personaplex-7b-v1-greedy.safetensors
//! ```

use std::{collections::HashMap, path::PathBuf};

use eredu_backend_mlx::native::{
    ops::{indexing::TryIndexOp, stack_axis},
    Array, Device, DeviceType, ExecutionContext, Stream,
};
use eredu_backend_mlx::{MlxRealtimeBackend, MlxRealtimeInput};
use eredu_core::scheduler::{RequestId, SchedulerLimits};
use eredu_core::{load_realtime_model, RealtimeSampling, RealtimeScheduler};

fn main() -> anyhow::Result<()> {
    let args = std::env::args().skip(1).collect::<Vec<_>>();
    let model_dir = args
        .first()
        .map(PathBuf::from)
        .expect(
            "usage: personaplex_torch_parity <released-personaplex-7b-v1-artifact-dir> <fixture.safetensors>",
        );
    let fixture_path = args
        .get(1)
        .map(PathBuf::from)
        .expect("missing PersonaPlex PyTorch fixture path");

    let gpu = ExecutionContext::new(Device::new(DeviceType::Gpu, 0));
    let cpu = ExecutionContext::new(Device::new(DeviceType::Cpu, 0));
    let stream = gpu.stream();
    let fixture = Array::load_safetensors(&fixture_path, cpu.stream())?;
    let input_audio = required(&fixture, "generation.input_audio")?;
    let expected_sampled = required(&fixture, "generation.expected_sampled")?;
    let expected_output_audio = required(&fixture, "generation.expected_output_audio")?;
    let expected_emitted_steps = required(&fixture, "generation.expected_emitted_steps")?;

    let mut model = load_realtime_model(MlxRealtimeBackend::new(stream, cpu.stream()), &model_dir)?;
    let generated_audio_codebooks = model.speech_config().generated_audio_codebooks() as i32;
    let request = RequestId::new(1);
    let mut scheduler = RealtimeScheduler::new(&model, SchedulerLimits::new(1, 1)?)?;
    scheduler.register_request(&model, request, RealtimeSampling::greedy())?;
    let mut sampled = Vec::new();
    let mut emitted = Vec::new();
    let mut emitted_steps = Vec::new();
    for step in 0..input_audio.dim(2) {
        let input = input_audio.try_index_device((.., .., step), stream)?;
        scheduler.enqueue(&model, request, MlxRealtimeInput::encoded_audio(&input))?;
        let output = loop {
            if let Some(output) = scheduler.run_queued(&mut model)?.pop() {
                break output.into_parts().1;
            }
            std::thread::yield_now();
        };
        if step > 0 {
            let text = output.text_token.squeeze_axes(&[-1], stream)?;
            let text = text.expand_dims(1, stream)?;
            let frame = eredu_backend_mlx::native::ops::concatenate_axis(
                &[text, output.sampled_audio_tokens],
                1,
                stream,
            )?;
            sampled.push(frame);
        }
        if let Some(tokens) = output.output_audio_tokens {
            emitted.push(tokens);
            emitted_steps.push(step);
        }
    }

    let actual_sampled = if sampled.is_empty() {
        Array::zeros::<i32>(&[input_audio.dim(0), 17, 0], stream)?
    } else {
        stack_axis(&sampled, 2, stream)?
    };
    let actual_output_audio = if emitted.is_empty() {
        Array::zeros::<i32>(&[input_audio.dim(0), generated_audio_codebooks, 0], stream)?
    } else {
        stack_axis(&emitted, 2, stream)?
    };
    let actual_emitted_steps =
        Array::from_slice(&emitted_steps, &[i32::try_from(emitted_steps.len())?]);
    anyhow::ensure!(
        expected_sampled.dim(1) == generated_audio_codebooks + 1,
        "released fixture sampled width must be text plus {generated_audio_codebooks} generated audio codebooks, got {}",
        expected_sampled.dim(1)
    );
    compare_tokens(
        &actual_sampled,
        expected_sampled,
        stream,
        "sampled model tokens",
    )?;
    compare_tokens(
        &actual_output_audio,
        expected_output_audio,
        stream,
        "delay-aligned output audio",
    )?;
    compare_tokens(
        &actual_emitted_steps,
        expected_emitted_steps,
        stream,
        "emitted frame positions",
    )?;

    println!(
        "PersonaPlex PyTorch parity passed: {} input frames, {} sampled frames, {} emitted frames",
        input_audio.dim(2),
        actual_sampled.dim(2),
        actual_output_audio.dim(2)
    );
    Ok(())
}

fn required<'a>(fixture: &'a HashMap<String, Array>, key: &str) -> anyhow::Result<&'a Array> {
    fixture
        .get(key)
        .ok_or_else(|| anyhow::anyhow!("fixture is missing tensor {key}"))
}

fn compare_tokens(
    actual: &Array,
    expected: &Array,
    stream: &Stream,
    label: &str,
) -> anyhow::Result<()> {
    anyhow::ensure!(
        actual.shape() == expected.shape(),
        "{label}: shape mismatch: Rust {:?}, upstream {:?}",
        actual.shape(),
        expected.shape()
    );
    let expected = expected.copy(stream)?;
    let equal = actual.eq(&expected, stream)?.all(None, stream)?;
    anyhow::ensure!(equal.item::<bool>(stream), "{label}: token mismatch");
    Ok(())
}
