//! Compare the MLX realtime backend with a released PersonaPlex 7B-v1
//! PyTorch fixture generated by `eredu/scripts/personaplex_torch_fixture.py`.
//!
//! Generate and run explicitly:
//!
//! ```text
//! python eredu/scripts/personaplex_torch_fixture.py \
//!   --artifact-dir /models/personaplex-7b-v1 \
//!   --checkpoint /models/personaplex-7b-v1 \
//!   --personaplex-source /src/personaplex \
//!   --moshi-source /src/kyutai-moshi/moshi \
//!   --require-torch-version VERSION \
//!   --output /fixtures/personaplex-7b-v1-greedy.safetensors
//! cargo run -p eredu-backend-mlx --example personaplex_torch_parity -- \
//!   /models/personaplex-7b-v1 /fixtures/personaplex-7b-v1-greedy.safetensors
//! ```

use std::{collections::HashMap, path::PathBuf};

use eredu_backend_mlx::native::{Array, Device, DeviceType, ExecutionContext, Stream};
use eredu_backend_mlx::{native::MlxRealtimeBackend, MlxTensor};
use eredu_core::{load_realtime_model, ObservationSet, ObservationValue, RealtimeSampling};
use eredu_evaluation::{
    compare_observations, encoded_audio_frames, observe_i32_tensor, run_realtime_trace,
    ParityPolicy,
};

fn main() -> anyhow::Result<()> {
    let args = std::env::args().skip(1).collect::<Vec<_>>();
    let model_dir = args
        .first()
        .map(PathBuf::from)
        .expect(
            "usage: personaplex_torch_parity <released-personaplex-7b-v1-artifact-dir> <fixture.safetensors>",
        );
    let fixture_path = args
        .get(1)
        .map(PathBuf::from)
        .expect("missing PersonaPlex PyTorch fixture path");

    let gpu = ExecutionContext::new(Device::new(DeviceType::Gpu, 0));
    let cpu = ExecutionContext::new(Device::new(DeviceType::Cpu, 0));
    let stream = gpu.stream();
    let fixture = Array::load_safetensors(&fixture_path, cpu.stream())?;
    let input_audio = required(&fixture, "generation.input_audio")?;
    let expected_sampled = required(&fixture, "generation.expected_sampled")?;
    let expected_output_audio = required(&fixture, "generation.expected_output_audio")?;
    let expected_emitted_steps = required(&fixture, "generation.expected_emitted_steps")?;

    let preparation = eredu_architectures::moshi::prepare_realtime_model(&model_dir)?;
    let mut model =
        load_realtime_model(MlxRealtimeBackend::new(stream, cpu.stream()), preparation)?;
    let generated_audio_codebooks = model.speech_config().generated_audio_codebooks();
    let trace = run_realtime_trace(
        &mut model,
        encoded_audio_frames(&MlxTensor::from_array(input_audio.clone()), stream)?,
        RealtimeSampling::greedy(),
    )
    .map_err(|error| anyhow::anyhow!(error.to_string()))?;
    anyhow::ensure!(
        expected_sampled.dim(1) == i32::try_from(generated_audio_codebooks + 1)?,
        "released fixture sampled width must be text plus {generated_audio_codebooks} generated audio codebooks, got {}",
        expected_sampled.dim(1)
    );
    let trace_observations = trace.observations()?;
    let mut actual = ObservationSet::new();
    actual.insert(
        "generation.sampled",
        ObservationValue::Tensor(trace.combined_sampled_tokens(1)?),
    )?;
    actual.insert(
        "generation.output_audio",
        trace_observations
            .get("trace.output_audio_tokens")
            .cloned()
            .ok_or_else(|| anyhow::anyhow!("trace omitted output audio"))?,
    )?;
    actual.insert(
        "generation.emitted_steps",
        ObservationValue::Tensor(trace.emitted_frame_indices()?),
    )?;
    let mut reference = ObservationSet::new();
    insert_tokens(
        &mut reference,
        "generation.sampled",
        expected_sampled,
        stream,
    )?;
    insert_tokens(
        &mut reference,
        "generation.output_audio",
        expected_output_audio,
        stream,
    )?;
    insert_tokens(
        &mut reference,
        "generation.emitted_steps",
        expected_emitted_steps,
        stream,
    )?;
    let report = compare_observations(&actual, &reference, &ParityPolicy::exact())?;
    anyhow::ensure!(report.passed, "token parity failed: {:?}", report.failures);

    println!(
        "PersonaPlex PyTorch parity passed: {} input frames, {} sampled frames, {} emitted frames",
        input_audio.dim(2),
        trace.frames().len().saturating_sub(1),
        trace
            .frames()
            .iter()
            .filter(|frame| frame.output_audio_tokens().is_some())
            .count()
    );
    Ok(())
}

fn required<'a>(fixture: &'a HashMap<String, Array>, key: &str) -> anyhow::Result<&'a Array> {
    fixture
        .get(key)
        .ok_or_else(|| anyhow::anyhow!("fixture is missing tensor {key}"))
}

fn insert_tokens(
    observations: &mut ObservationSet,
    path: &str,
    value: &Array,
    stream: &Stream,
) -> anyhow::Result<()> {
    let value = MlxTensor::from_array(value.clone());
    observations.insert(
        path,
        ObservationValue::Tensor(observe_i32_tensor(&value, stream)?),
    )?;
    Ok(())
}
